- hosts: ubuntu
  gather_facts: false
  tasks:
    - name: Update apt package list
      become: true
      apt:
        force_apt_get: true
        update_cache: true
    - name: Install apt packages
      become: true
      apt:
        name: 
          - git
          - curl
          - openssh-server

- hosts: mac
  gather_facts: false
  tasks:
    - name: Update brew package list 
      homebrew:
        update_homebrew: true
    - name: Install brew packages
      homebrew:
        name:
          - git
          - curl

- hosts: all
  gather_facts: false
  tasks:
    - name: Clone dotfiles
      git:
        repo: git@github.com:totto2727-org/dotfiles.git
        dest: "{{ home_dir }}/dotfiles"
        clone: true
        update: "{{ update_dotfiles }}"

    - name: Clone ssh_config
      git:
        repo: git@github.com:totto2727/ssh_config.git
        dest: "{{ home_dir }}/ssh_config"
        clone: true
        update: true
    - name: Make .ssh directory
      file:
        path: "{{ home_dir }}/.ssh"
        state: directory
        mode: "755"
    - name: Make links in .ssh
      file:        
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      loop:
        - dest: "{{ home_dir }}/.ssh/authorized_keys"
          src: "{{ home_dir }}/ssh_config/authorized_keys"
        - dest: "{{ home_dir }}/.ssh/config"
          src: "{{ home_dir }}/ssh_config/config"

    - name: Clone git_config
      git:
        repo: git@github.com:totto2727/git_config.git
        dest: "{{ home_dir }}/git_config"
        clone: true
        update: true
    - name: Make links to .git
      file:
        src: "{{ home_dir }}/git_config"
        dest: "{{ home_dir }}/.git"
        state: link
        force: true

- hosts: ubuntu
  gather_facts: false
  tasks:
    - name: Make link of sshd_config
      become: true
      file:
        src: "{{ home_dir }}/ssh_config/sshd_config"
        dest: /etc/ssh/sshd_config
        state: link
        force: true
    - name: Reload sshd
      become: true
      systemd:
        name: sshd
        state: reloaded



